version: '3.7'
services:
  app:
    build: .
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
      - "8081:8081"
    volumes:
      - .:/app
      - /app/node_modules
    command: npx expo start
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0